# Generated by Django 2.1.2 on 2018-10-14 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_blog_it', '0015_auto_20180304_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facebook',
            name='user',
        ),
        migrations.RemoveField(
            model_name='google',
            name='user',
        ),
        migrations.DeleteModel(
            name='Facebook',
        ),
        migrations.DeleteModel(
            name='Google',
        ),
    ]
