# Generated by Django 2.1.1 on 2018-10-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_blog_it', '0015_auto_20180304_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='featured_image',
        ),
        migrations.AddField(
            model_name='post',
            name='avg_time',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
