# Generated by Django 2.1.1 on 2018-10-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_blog_it', '0017_post_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='no_of_views',
            field=models.CharField(blank=True, default='0', max_length=3),
        ),
    ]
