# Generated by Django 2.1.1 on 2018-10-21 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_blog_it', '0018_post_no_of_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='no_of_views',
        ),
    ]
